/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CreateRequest = IDL.Record({
  'title' : IDL.Text,
  'link' : IDL.Opt(IDL.Text),
  'description' : IDL.Text,
  'series' : IDL.Text,
  'imageUrl' : IDL.Opt(IDL.Text),
});
export const Id = IDL.Nat;
export const Timestamp = IDL.Int;
export const ComicEntry = IDL.Record({
  'id' : Id,
  'title' : IDL.Text,
  'link' : IDL.Opt(IDL.Text),
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'series' : IDL.Text,
  'imageUrl' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  'createComicEntry' : IDL.Func([CreateRequest], [ComicEntry], []),
  'getComicEntry' : IDL.Func([Id], [ComicEntry], ['query']),
  'listComicEntries' : IDL.Func([], [IDL.Vec(ComicEntry)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CreateRequest = IDL.Record({
    'title' : IDL.Text,
    'link' : IDL.Opt(IDL.Text),
    'description' : IDL.Text,
    'series' : IDL.Text,
    'imageUrl' : IDL.Opt(IDL.Text),
  });
  const Id = IDL.Nat;
  const Timestamp = IDL.Int;
  const ComicEntry = IDL.Record({
    'id' : Id,
    'title' : IDL.Text,
    'link' : IDL.Opt(IDL.Text),
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'series' : IDL.Text,
    'imageUrl' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    'createComicEntry' : IDL.Func([CreateRequest], [ComicEntry], []),
    'getComicEntry' : IDL.Func([Id], [ComicEntry], ['query']),
    'listComicEntries' : IDL.Func([], [IDL.Vec(ComicEntry)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };